//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcball_3dRotation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arcball_3dRotation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### 10x10 CUBE Generated by Samson Mano &lt;saminnx@gmail.com&gt;
        ///$$$$ SCALE, 40
        ///$$$$ POINTS
        ///         1,  5.0            ,  2.0            ,  -5.0           
        ///         2,  5.0            ,  1.0            ,  -5.0           
        ///         3,  5.0            ,  0.0            ,  -5.0           
        ///         4,  5.0            ,  -1.0           ,  -5.0           
        ///         5,  5.0            ,  -2.0           ,  -5.0           
        ///         6,  5.0            ,  -3.0           ,  -5.0           
        ///         7,  5.0          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cube_1 {
            get {
                return ResourceManager.GetString("cube_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### CYLINDER Generated by Samson Mano &lt;saminnx@gmail.com&gt;
        ///$$$$ SCALE, 20
        ///$$$$ POINTS
        ///         1,  -2.44929360E-15,  10.0           ,  10.0           
        ///         2,  -1.044949031495,  10.0           ,  9.9367544086102
        ///         3,  -2.077588728473,  10.0           ,  9.7739238594229
        ///         4,  -3.089276100123,  10.0           ,  9.5091776851476
        ///         5,  -4.063346381418,  10.0           ,  9.1267932065025
        ///         6,  -4.994521157268,  10.0           ,  8.6513883457532
        ///         7,  -5.87510027468 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cylinder_1 {
            get {
                return ResourceManager.GetString("cylinder_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### DONUT Generated by Samson Mano &lt;saminnx@gmail.com&gt;
        ///$$$$ SCALE, 20
        ///$$$$ POINTS
        ///         1,  0.0            ,  0.0            ,  0.0            
        ///         2,  -2.44929360E-15,  0.0            ,  10.0           
        ///         3,  -2.44929360E-15,  0.0            ,  6.0            
        ///         4,  -2.44929360E-15,  0.6945927106677,  6.0607689879512
        ///         5,  -2.44929360E-15,  1.3680805733027,  6.2412295168564
        ///         6,  -2.44929360E-15,  2.0            ,  6.5358983848623
        ///         7,  -2.44929360E-15,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string donut_1 {
            get {
                return ResourceManager.GetString("donut_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### Klein Bottle Generated by Samson Mano &lt;saminnx@gmail.com&gt;
        ///$$$$ SCALE, 20
        ///$$$$ POINTS
        ///         1,  1.5641443134104,  3.142003195    ,  -0.249578701008
        ///         2,  1.4993095916363,  2.9653811117217,  -0.128885062336
        ///         3,  1.548719720033 ,  2.9631469974678,  -0.249157217826
        ///         4,  2.4428468183708,  2.7181565782055,  -0.128631020472
        ///         5,  2.3937070908729,  2.7215424358638,  -0.248804652596
        ///         6,  2.3151917525269,  2.727120214516 ,  -0.352461191499
        ///         7,  2.21233671 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string klein_bottle_1 {
            get {
                return ResourceManager.GetString("klein_bottle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### 10x10 Sphere Generated by Samson Mano &lt;saminnx@gmail.com&gt;
        ///$$$$ SCALE, 40
        ///$$$$ POINTS
        ///         1,  5.0            ,  0.0            ,  0.0            
        ///         2,  4.9726094768414,  0.0            ,  0.5226423163383
        ///         3,  4.890738003669 ,  0.0            ,  1.0395584540888
        ///         4,  4.7552825814756,  0.0            ,  1.5450849718753
        ///         5,  4.567727288213 ,  0.0            ,  2.033683215379 
        ///         6,  4.3301270189222,  0.0            ,  2.5            
        ///         7,  4.04508497 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sphere_1 {
            get {
                return ResourceManager.GetString("sphere_1", resourceCulture);
            }
        }
    }
}
